### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by hardiktheprogrammer** [starknet-io/starknet-docs#1005]
**Describe the bug**
Encountered a broken or invalid link in the Starknet Docs repository. The link to the Starknet Docs team appears to be dysfunctional, 
[starknet doc Team ](https://github.com/orgs/starknet-io/teams/starknet-docs)

**Comment by stoobie** [comment]
@hardiktheprogrammer This group is really just for admins. But I'm curious where you saw a broken link?

**Comment by hardiktheprogrammer** [comment]
> @hardiktheprogrammer This group is really just for admins. But I'm curious where you saw a broken link?

"Oops! My mistake – I meant to type something else. Apologies for the confusion. No broken link; it was a typo.
