### ISSUE TITLE
*Seeking Contribution* Add list of contributors

### ISSUE THREAD

**Issue by stoobie** [starknet-io/starknet-docs#1042]
Add a list of contributors. Ideally, this would be automatically updated. If you know how to do this, such a contribution would be very much appreciated!

Ideally, you should be able to see a list of contributors on each published page, like the **See contributors** button in the developer documentation on  Ethereum.org:
![image](https://github.com/starknet-io/starknet-docs/assets/39279277/bda229b0-0a3e-4fb2-bdb8-0744db7f1368)

  **TIP**
  From @omahs: 
  > For the Contributors list, this tool is used on many repos: https://allcontributors.org/

This contribution is eligible for funding via OnlyDust. If you are interested in taking on this PR, please leave a comment to let me know.

**Comment by gianalarcon** [comment]
I would like to try this one.

I can start adding a Contributors list, using https://allcontributors.org/

Like we did on the [starknet-book](https://github.com/starknet-edu/starknetbook?tab=readme-ov-file#contributors-)

**Comment by xiaolou86** [comment]
@stoobie I would like to try this one.

The following is my basic thought:
1. add a contributors list, by using https://allcontributors.org/.
2. add Last Edit and a list of contributors on each published page, by updating antora ui to get contributors information automatically.

**Comment by stoobie** [comment]
@gianalarcon @xiaolou86 What I'm really going for is the example I showed from the Ethereum site. On the Starknet Book, I only see a list of contributors on the Github repo, and only on the home page of the repo.

**Comment by xiaolou86** [comment]
My main thought is fetching Last Edit and Contributors automatically and add them to [antora ui](https://github.com/starknet-io/starknet-docs-antora-ui)

**Comment by xiaolou86** [comment]
hello @stoobie , I have some free time and can I take a try?

**Comment by stoobie** [comment]
@xiaolou86 Sure, I'll assign it to you.

**Comment by xiaolou86** [comment]
Thank you

**Comment by stoobie** [comment]
@xiaolou86 Are you in the Telegram group?

**Comment by xiaolou86** [comment]
@stoobie No, I am not. And I rarely use Telegram.

**Comment by fishonamos** [comment]
This is due! I will raise a pr for it? @stoobie Did a similar task for [StarkNet Quest.](https://github.com/starknet-id/starknet.quest/pull/546)

**Comment by xiaolou86** [comment]
@stoobie I think I have finished in here https://github.com/starknet-io/starknet-docs-antora-ui/pull/39. 

Please help me to review.

**Comment by stoobie** [comment]
@xiaolou86 Great! I'll take a look next week.
