### ISSUE TITLE
*Seeking Contribution* Add Glossary

### ISSUE THREAD

**Issue by stoobie** [starknet-io/starknet-docs#1062]

**Comment by LevisNgigi** [comment]
Hey, is there a definition for the above terms somewhere or I will just have to do my research and add them in relation to Starknet?

**Comment by coburn24** [comment]
@LevisNgigi thats what we need to add 🙂 a little research through the docs and should be able to come up with a definition

**Comment by LevisNgigi** [comment]
okay let me have a look

**Comment by coburn24** [comment]
@LevisNgigi just so we're not working on the same ones, my PR will include RPC, API, components, arrays, dictionaries, signers, multi-call, import

**Comment by LevisNgigi** [comment]
okay that is fine I will work on the rest

**Comment by coburn24** [comment]
PR sent to the [docs-common-content](https://github.com/starknet-io/docs-common-content/blob/main/modules/ROOT/partials/partial_glossary.adoc) @stoobie

**Comment by Antismart** [comment]
Hey can I work on this?

**Comment by coburn24** [comment]
@Antismart you can work on it, I shared a PR with what I worked on, @LevisNgigi said he's working on the rest but @stoobie is the guy to merge PR's

shoot a PR, and if you have more ideas for what terms we can add to the glossary please share them with us.

**Comment by stoobie** [comment]
@Antismart @coburn24 @LevisNgigi Fantastic, thank you! I'll take a look at your PRs.

**Comment by stoobie** [comment]
@Antismart @LevisNgigi Please take a look at the updated list before you begin working. I see that unfortunately there's already been some duplication of effort.

**Comment by LevisNgigi** [comment]
I have opened a PR with a few terms.

**Comment by 0xcoburn** [comment]
I can help check some more of these off @stoobie 
I'll do node, full node, fri. Not sure what g fri is and are sry(sorry) and fren (friend) for real? Haha

**Comment by stoobie** [comment]
> I can help check some more of these off @stoobie I'll do node, full node, fri. Not sure what g fri is and are sry(sorry) and fren (friend) for real? Haha

Hey @0xcoburn G-fri is Gigafri. I'm removing sry and fren :fearful:

**Comment by 0xcoburn** [comment]
cool, didn't know we were referring to the smallest unit of STRK as fri 🍟 I like it

thought FRI was referring to the polynomial commitment scheme STARK's use (Fast Reed-Soloman interactive oracle proofs of proximity)

**Comment by ivpavici** [comment]
Just to bump this! 
A glossary will be very helpful to newcomers - since the docs are full of very specific technical terms (for example, going through this [page ](https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/) about fees, one might wonder what is a `builtin` etc. ?)

**Comment by LevisNgigi** [comment]
Just to mention as well,my pr was approved but never merged.

**Comment by stoobie** [comment]
@LevisNgigi @0xcoburn @Hug0x0 I apologize both for lack of communication and for this taking so long.

I merged your separate PRs into one larger PR, edited it and I've been getting folks to review the definitions before it's approved for posting. It's taken much longer than I expected, but I will post something this week, even if not everything.

**Comment by LevisNgigi** [comment]
Okay that will be fine,I appreciate it.

**Comment by stoobie** [comment]
#1095 in this repo together with https://github.com/starknet-io/docs-common-content/pull/18 close this issue.

Thank you for your contributions @0xcoburn @LevisNgigi and @Hug0x0!

**Comment by LevisNgigi** [comment]
Welcome.
