### ISSUE TITLE
Request for Contribution: L1-L2 Messaging programming reference

### ISSUE THREAD

**Issue by stoobie** [starknet-io/starknet-docs#1086]
_Please reply in the comments if you are interested._

# Description

Document the L1 functions and L1 events that enable L1->L2 messaging. Include general descriptions of the contracts that include the functions. For example, see the [StarkGate function and event reference](https://docs.starknet.io/documentation/tools/starkgate_function_reference/)

## For each _function_, include the following information:

- `<function name>`
- **Description**: An in-depth description of the function that includes:
  - What does the function do?
  - Why does it matter?
  - Any other information that is necessary or useful to know.
- **State mutability**: `Pure`/`payable`/`non-payable`/`view`
- **Parameters**: For each parameter: <type> <param name>:: <Description>. If there are no parameters, specify None.
- **Return values**: Same as Parameters. If there are no return values, specify None.
- **Function definitions**: Links to the function interfaces within the contract, and to the function implementations.

Examples: [`deposit`](https://docs.starknet.io/documentation/tools/starkgate_function_reference/#deposit),  [`getStatus`](https://docs.starknet.io/documentation/tools/starkgate_function_reference/#getStatus), and others in the _StarkGate function and event reference_.

## For each _event_, include the following information:

- `<event name>`
- **Description**: 
  - What does the function do?
  - Why does it matter?
  - Any other information that is necessary or useful to know.
- **Event attributes**: List attributes of the event.

Examples: See **Emitted event** and **Event attributes** in [`depositCancelRequest`](https://docs.starknet.io/documentation/tools/starkgate_function_reference/#depositCancelRequest), [`withdraw`](https://docs.starknet.io/documentation/tools/starkgate_function_reference/#withdraw), and others  in the _StarkGate function and event reference_.

**NOTE:** In these examples, the events are directly tied to the relevant functions. For the Messaging event reference, the events should have their own dedicated section.

## Source material

- You can find the interfaces for these functions in [IStarknetMessaging.sol](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessaging.sol)
- L1 Events: [IStarknetMessagingEvents.sol](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/IStarknetMessagingEvents.sol)
- L1 Function implementations (For the implementation, you just need to provide a link to the implementation, nothing more): [StarknetMessaging.sol](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/solidity/StarknetMessaging.sol).

# Instructions for Contributing

1. Leave a comment on this Issue indicating that you want to take ownership of this feature.
2. Wait for our confirmation to start on the project.
3. Once you have received confirmation, begin working on your contribution in a new branch.
4. Create a new AsciiDoc file named `messaging_reference.adoc` in `components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture`. Use the code in the Template code section. Stick to this format.
5. Add the new file to the table of contents by adding an `xref` to it in `components/Starknet/modules/architecture_and_concepts/nav.adoc`
6. Follow these [basic writing guidelines](https://github.com/starknet-io/starknet-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#basic-writing-guidelines).
6. Be ready to make changes based on review comments.

## AsciiDoc Function Template

```
[id=”messaging_reference”]
= Messaging reference

== L1 Function reference
'''

[#function_name]
=== `<function_name>`

[discrete]
==== Description

<Add text for description here>

[discrete]
==== State Mutability

`payable` | `non-payable` | `view` | `pure`

[discrete]
==== Parameters

[horizontal,labelwidth="30",role=stripes-odd]
`<type> _<param_name>_`:: <Description>

[discrete]
==== Returns

This section should include a list of return values and what they mean in the same format as Parameters:

[horizontal,labelwidth="30",role=stripes-odd]
`<type> _<return_value>_`:: <Description>


[discrete]
==== Function definitions

Contract: link:<URL>[`<filename>.sol`]

* Function: link:<URL_permalink>[`<function_name>`]

```

## AsciiDoc Event Template

Add this below all functions

```
== L1 Event reference

Add link to contract here.

[#event_name]
=== `<event_name>`

[discrete]
==== Description

<Add text for description here, including what triggers this event.>

[discrete]
==== Event attributes

[horizontal,role=stripes-odd]
`<type> _<attribute_name>_`:: <Description>.

[discrete]
==== Event definition

* Contract: link:<URL_of_contract>[`<contract_name>`]

* Event: link:<permalink_to_event>[`<event_name>`]
```

# Remuneration

Compensation for the approved contribution will be provided via OnlyDust.

# Deadline

Maximum of 10 days per example

# Contact

If you have any questions or need further details, please contact @stoobie.

__________________
We look forward to your proposals. Thank you for contributing to the Starknet ecosystem!

**Comment by xiaolou86** [comment]
@stoobie I am interested in starknet, and want to take ownership of this feature. Thank you.

**Comment by stoobie** [comment]
@xiaolou86 Thank you for volunteering! It's yours. Go ahead and begin. Please make sure you read all the guidelines above and see the examples that I linked to.

Let me know if you have any questions.

**Comment by xiaolou86** [comment]
> @xiaolou86 Thank you for volunteering! It's yours. Go ahead and begin. Please make sure you read all the guidelines above and see the examples that I linked to.
> 
> Let me know if you have any questions.

Got it.
