### ISSUE TITLE
Feature Request : Add FAQ

### ISSUE THREAD

**Issue by A-coolcreator** [starknet-io/starknet-docs#1088]
**Is your feature request related to a problem? Please describe.**
 Add FAQ

***Questions to address in FAQ***

-  Why was an alpha version released instead of directly launching the production version (referring to Starknet)?
- What is the expected TPS in the future production version, or what is the estimated maximum TPS for the L2 developed by STARKs?
- Why is the actual transaction completion time different from the estimated transaction time within the explorer?
- Is it necessary to wait for the status to become 'accepted on L1' for a transaction to be considered complete?
- Is it possible to manually increase gas fees to speed up transactions?
- Why does it take so long for withdrawals using Starkgate to be credited, and why is an Ethereum gas fee still required?

**Comment by A-coolcreator** [comment]
@stoobie can you please assign me this task i would like to work on this

**Comment by stoobie** [comment]
@A-coolcreator Sure.

Please use the following code:

```
[id="FAQ"]
= Frequently asked questions

[id="FAQ"]

[#<question>
== <Question>

<Answer>
```

**Comment by hardiktheprogrammer** [comment]
@stoobie  I would like to contribute on this

**Comment by stoobie** [comment]
@hardiktheprogrammer I think that [this FAQ on the Starknet site](https://www.starknet.io/en/learn/frequently-asked-questions) already addresses most of the questions and we can send them more questions if there are any missing.

WDYT?

**Comment by hardiktheprogrammer** [comment]
7)How can I participate in voting if I don't have tokens?
8)Why are tokens deployed on Ethereum rather than on Starknet?
9)Why is it necessary to use Cairo instead of directly using Solidity?

**Comment by hardiktheprogrammer** [comment]
> @hardiktheprogrammer @A-coolcreator:
> 
> > @hardiktheprogrammer I think that [this FAQ on the Starknet site](https://www.starknet.io/en/learn/frequently-asked-questions) already addresses most of the questions and we can send them more questions if there are any missing.
> > WDYT?
> 
> As far as I can tell, the existing FAQ is enough. If you don't agree, please explain why.

I concur that the existing FAQ is adequate; however, integrating it into the Starknet documentation would be advantageous, allowing developers to comprehend and access all the information contained within the FAQ seamlessly through the official Starknet documentation.

**Comment by stoobie** [comment]
Closing this as we decided that it's covered in the existing FAQ.
