### ISSUE TITLE
Request for Contribution: Add a page explaining the Compiled class hash

### ISSUE THREAD

**Issue by stoobie** [starknet-io/starknet-docs#1090]
_Please reply in the comments if you are interested._

# Description
The Starknet docs explains the [Class hash](https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/class-hash/), but not the Compiled class hash. We need a similar page for the Compiled class hash that describes:

* What it is, why it exists
* Which entities use it, in what context
* Make sure to state that you need to generate it somehow, such as with an SDK, before you can send a `DECLARE` transaction.
* How an SDK and the sequencer calculate the compiled class hash, pseudo code is fine, as in [Computing the Cairo class hash](https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/class-hash/#computing_the_cairo_1_class_hash).
* Use the information in the Note in commit bc419f6cfa7f3ce5e0054313b720299e12800bf2 at line 107.

# Instructions for Contributing
1. Leave a comment on this Issue indicating that you want to take ownership of this feature.
2. Wait for our confirmation to start on the project.
3. Once you have received confirmation, begin working on your contribution in a new branch.
4. Create a new AsciiDoc file named `compiled_class_hash.adoc` in `components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts`. 
5. Add the new file to the table of contents by adding an `xref` to it in `components/Starknet/modules/architecture_and_concepts/nav.adoc`
6. Follow these [basic writing guidelines](https://github.com/starknet-io/starknet-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#basic-writing-guidelines).
7. Be ready to make changes based on review comments.
# Remuneration
Compensation for the approved contributions will be provided via OnlyDust.
# Deadline
Maximum of 10 days
# Contact
If you have any questions or need further details, please contact @stoobie.
_____
We look forward to your proposals. Thank you for contributing to the Starknet ecosystem!

**Comment by stoobie** [comment]
@hardiktheprogrammer  Thank you for volunteering! It's yours. Go ahead and begin. Please make sure you read all the guidelines above and see the examples that I linked to.

**Comment by hardiktheprogrammer** [comment]
> @hardiktheprogrammer Thank you for volunteering! It's yours. Go ahead and begin. Please make sure you read all the guidelines above and see the examples that I linked to.

Thanks ser

**Comment by stoobie** [comment]
@hardiktheprogrammer I am unassigning this. If you find that you can do this before someone else takes ownership, please let me know and I can reassign it to you.

**Comment by xiaolou86** [comment]
Hello @stoobie , I want to take ownership of this feature.
I like the starknet-docs, it let me learn more day by day, and make money meanwhile ^.^

**Comment by stoobie** [comment]
Hey @xiaolou86, I really appreciate your initiative and spirit. I'd like to finish the Builtins page before assigning you another issue.

**Comment by xiaolou86** [comment]
😸 🆗

**Comment by stoobie** [comment]
@raizo07 Can you show me samples of anything you've written?

**Comment by raizo07** [comment]
> @raizo07 Can you show me samples of anything you've written?
> 
> Also, feel free to join our [Telegram group](https://t.me/+9VC94EQA8dY4ZTZh)!

@stoobie I'm a member of the Telegram group already.

**Comment by juandiegocv27** [comment]
Hi @stoobie,

I am interested in taking ownership of this feature. I have also joined the Telegram group for further updates. It's my first contrution to this repo, but I also do documentation for anothers repo, like Dojo-Book. I'm very a searching info person, and love to talk about what to do.

**Comment by raizo07** [comment]
> https://github.com/strkfarm/starkfarm-client

Yeah I meant the README for Starkfarm and the Docusaurus model for Unruggable Meme. Yes I was assigned to both, of which I did the work and both PRs were merged. Also I tagged you on the telegram group with a raised hand.

**Comment by LandauRaz** [comment]
Closing this as it's been decided that it's no longer needed.

**Comment by LandauRaz** [comment]
Closed by #1294.
