### ISSUE TITLE
Add nonce definition to the docs

### ISSUE THREAD

**Issue by odednaor** [starknet-io/starknet-docs#1098]
The nonce of an address is the number of transactions originating from this address + 1. For example, the `starknet_getNonce` request of an account that was deployed (with nonce 0 in the deploy tx) but that did not send any transactions, should be 1.

**Comment by stoobie** [comment]
@odednaor Does this refer to the nonce of a user account?

**Comment by odednaor** [comment]
To any contract in Starknet, not only account contracts. What page in the docs should this be on?

**Comment by stoobie** [comment]
We mention it 

- under [Replay protection](https://docs.starknet.io/documentation/architecture_and_concepts/Accounts/approach/#replay_protection) for accounts: 
- under [Deploying new account>Transaction flow](https://docs.starknet.io/documentation/architecture_and_concepts/Accounts/deploying_new_accounts/#transaction_flow)

I think it should be in the glossary (needs to be added in #1095). This definition that you're referring to here relates specifically to contracts, not transactions, so what do you think about adding it under contract instances in https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/contract-classes/.
