### ISSUE TITLE
Request for Contribution: Describe Cairo builtins

### ISSUE THREAD

**Issue by stoobie** [starknet-io/starknet-docs#1126]
# Description
We need a page that describes what Cairo builtins are, what they do generally, and a list of builtins with a short description of what each one does specifically.

Explain what high-level Cairo code ends up invoking a given builtin? For example:

* `a&b` is a single application of the bitwise builtin. 
* `a>b` is a rangecheck.
# Source material

* The [builins page](https://docs.cairo-lang.org/how_cairo_works/builtins.html) from the CairoZero documentation.
* Gas and transaction fees>Fee calculation>Calculation of computation costs>[Table 1. Amount of gas used per Cairo step or per each time a Cairo builtin is applied](https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/#gas_cost_per_cairo_step_or_builtin_step)
* The files in this directory might also be useful: https://github.com/lambdaclass/cairo-vm/blob/352e8a8cb8addc267d8ae59073b6447fd8517c81/vm/src/vm/runners/builtin_runner
# Instructions for Contributing
1. Leave a comment on this Issue indicating that you want to take ownership of this feature.
2. Wait for our confirmation to start on the project.
3. Once you have received confirmation, begin working on your contribution in a new branch.
4. Create a new AsciiDoc file named `builtins.adoc` in `components/Starknet/modules/architecture_and_concepts/pages/Smart_Contracts`. 
5. Add the new file to the table of contents by adding an `xref` to it in `components/Starknet/modules/architecture_and_concepts/nav.adoc`
6. IMPORTANT: Do not simply copy and paste existing text in the source material above. Follow these [basic writing guidelines](https://github.com/starknet-io/starknet-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#basic-writing-guidelines). Some basic guidelines include: Use the active voice, not the passive voice, talk to your reader directly by using the second-person (you) and imperative. Use the present tense, avoid the future tense.
7. Be ready to make changes based on review comments.
# Remuneration
Compensation for the approved contributions will be provided via OnlyDust.
# Deadline
Maximum of 10 days
# Contact
If you have any questions or need further details, please contact @stoobie.
_____
We look forward to your proposals. Thank you for contributing to the Starknet ecosystem!

**Comment by BroManL** [comment]
wow

**Comment by xiaolou86** [comment]
Hello @stoobie , I want to take ownership of this feature. 

Is there an AsciiDoc Template for it? Thank you very much.

**Comment by vibenedict** [comment]
Hello, has anyone been assigned to it?
I would like to jump on it.

**Comment by stoobie** [comment]
Hey @xiaolou86 I just assigned you.

**Comment by stoobie** [comment]
> Hello, has anyone been assigned to it? I would like to jump on it.

Hi @vibenedict, I apologize for the confusion, I thought that this was already assigned. I'm very excited to know that you're interested in joining, and we'll have other contribution requests. In fact, if you see any

**Comment by xiaolou86** [comment]
@stoobie got it, and thank you.

I will try to write the framework in the following days, show you to confirm, and then write details.

**Comment by xiaolou86** [comment]
@stoobie I apologize for no significant progress by now, I will go faster. Hope it's not too late...

**Comment by LuckySamuraiX** [comment]
Здравствуйте, у кого то есть продвижение?

**Comment by stoobie** [comment]
> Здравствуйте, у кого то есть продвижение?

https://github.com/starknet-io/starknet-docs/pull/1243
