### ISSUE TITLE
The MathJax data formula style is disordered, with overlapping content

### ISSUE THREAD

**Issue by drgnchan** [starknet-io/starknet-docs#1144]
**Describe the bug**
The MathJax data formula style is disordered, with overlapping content.

**To Reproduce**

1. Go to https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/transactions/#v3_hash_calculation
2. scroll a little to the `data_availability_modes` description

**Expected behavior**
tidy formula style

**Screenshots**
<img width="1560" alt="Snipaste_2024-02-24_00-05-19" src="https://github.com/starknet-io/starknet-docs/assets/40224023/3aece60f-9dbf-4ca1-a852-b9dff9db5ffc">

**Desktop (please complete the following information):**

- OS: macOS 14.3.1 (23D60)
- Browser chrome
- Version 121.0.6167.184（正式版本） (arm64)

**Additional context**

**Comment by drgnchan** [comment]
When I change the MathJax script from "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-MML-AM_HTMLorMML" to "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js", the formula style is normal:

<img width="1233" alt="image" src="https://github.com/starknet-io/starknet-docs/assets/40224023/1cbe0931-1711-4bbc-b6ea-3490d118107d">

**Comment by stoobie** [comment]
Fixed in https://github.com/starknet-io/starknet-docs-antora-ui/pull/33

**Comment by stoobie** [comment]
Thanks for the pointer, @drgnchan!
