### ISSUE TITLE
Feature Request : Add more to FAQ

### ISSUE THREAD

**Issue by PizBernina** [starknet-io/starknet-docs#1157]
Would be highly appreciated to add more info regarding the fees that go to the Sequencer, rebates and burning mechanism.

1. What does the Sequencer do with the gas fees? (ETH or STRK)
 Wasn't able to answer it reading https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/fee-mechanism/. I believe that the Sequencer would use the tokens to cover the costs for it to be 'pushed' to Ethereum. But with v0.13.0, STRK tokens can be used, so are these atomically converted to ETH?
2. How exactly are rebates used for?
I found this https://medium.com/starkware/part-3-starknet-token-design-5cc17af066c6. However, are this meant to cover the airdrop claims? Thus, these will be swapped to ETH?
3. Is there any burning mechanism?
I believe just for withdrawing from L2->L1, right?

Thanks a lot and apologies if these were answered before. Didn't find them in the docs.

**Comment by stoobie** [comment]
@PizBernina Until someone gets around to creating an FAQ PR:

1. Sequencers convert the fees paid in STRK and sell them for ETH to cover operating costs. In practice, the operator of every sequencer chooses how to manage their finances, so they may convert frequently or infrequently.
Currently, the sequencer uses an ETH/STRK oracle to determine how many STRK tokens to charge its users as fee.
2. I'm still checking.
3. I believe you're correct, but this applies specifically to bridges. We describe the flow for the StarkGate bridge in the StarkGate bridge guide [Overview](https://docs.starknet.io/documentation/tools/starkgate-bridge/)

**Comment by mimiethetechsis** [comment]
Hello @stoobie, I did like to be assigned this. I am interested

**Comment by stoobie** [comment]
@mimiethetechsis Please feel free to create a PR for this.

Also feel free to join our our [Telegram group](https://t.me/+9VC94EQA8dY4ZTZh).

**Comment by stoobie** [comment]
Please make sure you review the repo's README, which includes information on contributing, writing guidelines, and style guidelines.

And feel free to ask me questions.

**Comment by mimiethetechsis** [comment]
Can i get a template for adding FAQ questions and what file do i add the questions to

**Comment by stoobie** [comment]
@mimiethetechsis Let's put an FAQ in the `ROOT/pages` directory.

As far as a template, please use this:

```
[id="FAQ"]
= Frequently asked questions

== Question 1?

Answer text 1.

[For more information, see...]

== Question 2?

Answer text 2.

[For more information, see...]

etc...
```
