### ISSUE TITLE
Add overview of all smart contracts involved and their users

### ISSUE THREAD

**Issue by PizBernina** [starknet-io/starknet-docs#1168]
Not sure where to ask/ request it, so I do it here.

I want to assess all smart contracts involved to make Starknet work, be it on L1 or Starknet.
This would include which users/ addresses have which rights.

Example contracts: STRK token contract on Ethereum, Starknet core contract, StarkGate, ...

I'd assume some external party did a review of them? Are these accessible to the public? The review would probably state such an overview.

Thanks a lot!

**Comment by stoobie** [comment]
@PizBernina Did you already check out the topic [Starknet contracts and sequencer addresses](https://docs.starknet.io/documentation/tools/important_addresses/)?

**Comment by stoobie** [comment]
@PizBernina I'm closing this issue, as I think that my previous reply answers your question. If not, then please reopen/make a new issue with more info, as mentioned in my previous comment.
