### ISSUE TITLE
feat: Reorganize and add info to Devtools page

### ISSUE THREAD

**Issue by stoobie** [starknet-io/starknet-docs#1223]
This item is to update the text and diagram on https://docs.starknet.io/documentation/tools/devtools/.

Add table/mini-toc to the beginning of topic with sections according to the categories in the diagram, as outlined below. The existing mini-toc, which appears on the right of the body pane on a desktop browser window, is according to tool name, not type of tool.

Suggested Outline (According to categories in diagram):

* Basic interaction with CLI, query-bolding tool (@amanusk please add the name of the tool here)
  * Starkli (also refer to Foundry Cast, but put the info under _Developing smart contracts_)
* Programming with SDKs and libraries
  * starknet.js
  * starknet.py
  * starknet-rs
  * starknet-go
  * starknet-React (New) @amanusk 
  * get-starknet (New) @amanusk 
* Developing smart contracts
   * Scarb
   * Starknet Foundry
   * Starknet Remix plugin (In the diagram, remove "Cairo plug-in)
   * Cairo language server (VS Code plugin)
   * Hardhat + Starknet (Maintenance mode only)
   * Cairo profiler (new @amanusk)
* Local devnet
   * starknet-devnet-rs
   * Katana
* Security tools (@amanusk Please add info)
* Bonus
   * ABI decoder
   * Universal Sierra compiler
   * @amanusk What else?

In addition, move _Who maintains it_ to the end of each section.

**Comment by hardiktheprogrammer** [comment]
@stoobie i m also interested in this task

**Comment by Osatuyi** [comment]
@stoobie please assign this to me.

**Comment by stoobie** [comment]
@hardiktheprogrammer Is the scope of this issue clear? Do you have any questions? There are several sections that require the input of @amanusk before they can be documented, but there are several items that you can work on already.

I am assigning this to you.

**Comment by stoobie** [comment]
@hardiktheprogrammer Please go ahead. @amanusk will be available to you for questions. Once you have implemented the reorganization of the topic as described above, @amanusk will add a draft of the new content mentioned in the issue description.

Please let me know if anything is unclear, or any questions you might have.

**Comment by amanusk** [comment]
Hey @hardiktheprogrammer ,

Some more useful links and tools that already exist or are currently being worked on:
* get-starknet: Library for connecting Dapps and wallets: https://github.com/starknet-io/get-starknet

* Starknet React: React hooks for Starknet: https://starknet-react.com/

* cairo-profiler: Profiler for Starknet contract and Cairo programs: https://github.com/software-mansion/cairo-profiler

* Security tools
* There is a list of tools here: https://github.com/amanusk/awesome-starknet-security
I believe we should only include tools working with Cairo 1 and up.
Relevant ones are Caracal, Aegis, sierra-analyzer. 

Please tag me here on in the PR with any additional information you need

**Comment by hardiktheprogrammer** [comment]
> @hardiktheprogrammer Is the scope of this issue clear? Do you have any questions? There are several sections that require the input of @amanusk before they can be documented, but there are several items that you can work on already.
> 
> I am assigning this to you.

Really sorry for late respons 

Right now i don't have any question if i have so I'll ask on telegram group chat


I wanna work on 
- scrab 
-  starknet foundry 
-  starknet remix
-  katana
- cairo language server 
-  starknet foundry

**Comment by hardiktheprogrammer** [comment]
> Hey @hardiktheprogrammer ,
> 
> Some more useful links and tools that already exist or are currently being worked on:
> 
> * get-starknet: Library for connecting Dapps and wallets: https://github.com/starknet-io/get-starknet
> * Starknet React: React hooks for Starknet: https://starknet-react.com/
> * cairo-profiler: Profiler for Starknet contract and Cairo programs: https://github.com/software-mansion/cairo-profiler
> * Security tools
> * There is a list of tools here: https://github.com/amanusk/awesome-starknet-security
>   I believe we should only include tools working with Cairo 1 and up.
>   Relevant ones are Caracal, Aegis, sierra-analyzer.
> 
> Please tag me here on in the PR with any additional information you need

I'll ask you questions through telegram @amanusk  is that okay

**Comment by amanusk** [comment]
feel free

**Comment by LandauRaz** [comment]
Closing this as the described reorganization is being reconsidered.
