### ISSUE TITLE
How to regain the trust of the community

### ISSUE THREAD

**Issue by maq24** [starknet-io/starknet-docs#1255]
**Is your feature request related to a problem? Please describe.**
If you've been on CT since the airdrop you have seen the constant FUD that is staining the starknet name which clearly is on a downward spiral.   We must prioritize community it has become abundantly clear that without community in web3 projects will always fail. Consider Starknet is the most technological advanced chain in web3 so how come people arent using it? Quite simple the community felt betrayed after the first airdrop which caused a feedback loop and now any tweet even mentioning starknet gets witch hunted. 

**Describe the solution you'd like**
The first priority needs to be how can we earn the communities trust back? This may seem like the most difficult step and it is, however once trust is reestablished the rest will all come together. As stated before Stark has the best tech of all the chains , people want to use it but they will likely never use it if the first airdrop is not fixed. Regardless of future airdrop rounds in the future this is not enough incentive for someone to return to a chain whom they believe betrayed them. My solution , reward users who were only not eligible due to the lack of .005 eth (the amount of $strk here does not matter) people will return to the chain as long as they feel they were not betrayed and the team is taking some steps to remedy the situation.

**Describe alternatives you've considered**
alternative solutions will be difficult because as long as the people from the first round are not rewarded with something, the stain on Starknet will remain. W e can assume most who were not eligible due to the .005 eth criteria are not plenty and then the others who were not eligible regardless of the .005 eth criteria. Secondary solution reward the users who would have been eligible if not for the .005 eth with the unclaimed $STRK tokens from the first airdrop.

**Additional context**
I have been in web3 for a long time and i know how this story ends, without community it is nearly impossible to succeed. Seeing a chain with superior tech like Starknet getting railroaded because of a minor mistake is a tough pill to swallow but by no means is it not fixable.

**Comment by maq24** [comment]
Oh I’m very sorry about that I wasn’t aware I’ll try posting it there

Appreciate the response.

**Comment by maq24** [comment]
It seems I can’t make any proposals there or even comment under any
discussions. Do you know how I can post in that forum ?

**Comment by maq24** [comment]
I have several great proposals but it feels like I'm not being
listened to at all. Starknet can be the leading chain of web3 but i can't
help but feel this continuous drive and prioritization for development is
causing a lot more harm than good.
 Starknet has the best tech of all the chains we are already leading in
that front yet day by day we are losing users. This should already prove to
you that tech without community

support and trust is meaningless. The team needs to start prioritizing ways
to earn back that  trust from the community. before it is too late.

**Comment by stoobie** [comment]
Hi @maq24 When you log in to the community forum, there's a **New Topic** button at the top. You can select under which category you want your comment to appear.

I'm closing this issue now, as this is not the correct forum. If you still are unable to post to the community forum, you can reach out via Discord. There's a Discord link in the footer of https://starknet.io.
