### ISSUE TITLE
Add the Cairo corelib repo URL to the list of important addresses

### ISSUE THREAD

**Issue by stoobie** [starknet-io/starknet-docs#1263]
From a user:

> I can't find a repo containing the core contracts from Starknet, though I have a vague memory of it existing. Can we get a repo of them linked on the _Important addresses_ topic or somewhere relevant?

Here's the directory with the Corelib source files:
https://github.com/starkware-libs/cairo/blob/v2.6.0/corelib/src/

Here's the main corelib file:
https://github.com/starkware-libs/cairo/blob/v2.6.0/corelib/src/starknet/info.cairo

**Comment by vibenedict** [comment]
Hi @stoobie, I can work on this.

**Comment by stoobie** [comment]
Ok, @vibenedict , go for it! You are now the assignee.

Let me know if you have any questions, or need help.

**Comment by AnmolSirola** [comment]
@stoobie Can I work on this issue?

**Comment by stoobie** [comment]
@LandauRaz

**Comment by LandauRaz** [comment]
Closing this as it's been decided that it's no longer needed.
