### ISSUE TITLE
Externalise ecosystem wide meeings

### ISSUE THREAD

**Issue by JorikSchellekens** [starknet-io/starknet-docs#1266]
It's important to the ecosystem that big discussions about the fundamentals of the network are open and that the progress of these features is in the collective mindshare. The community must know when an upgrade will happen and know how likely it is that a particular feature will be included. Currently, we rely on the StarkWare team's meticulous planning and coordination. By externailisg these conversations we make them easier to track and reduce the load on StarkWare and the Starknet Foundation. 

**Describe the solution you'd like**
Have a page dedicated to collecting ecosystem wide meeting calendars. Or just have a single calendar for it.
Here is the current one for the full node teams:

https://calendar.google.com/calendar/u/0?cid=YWIwNDlkOTZkNWY1ZjNlNWIwMDJmZDE3MTA3ZGFhZDRjYjNjYmUzNmFiY2I2NDg1MzFlZTVjNmMwOWNmNDNkMkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Describe alternatives you've considered**
There could possibly be an embedded calendar on starknet.io, but I think an easy-to-share calendar is more important.

**Comment by stoobie** [comment]
@JorikSchellekens Thanks for the idea. I'm passing this on the owner of starknet.io. This repo is only for docs.starknet.io, and I don't think this is the correct place for this.
