### ISSUE TITLE
Cover the SNIP process for Starknet

### ISSUE THREAD

**Issue by JorikSchellekens** [starknet-io/starknet-docs#1278]
**Is your feature request related to a problem? Please describe.**
A clear description of the SNIP process should be available on starknet.io (tracking [SNIP-1](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-1.md#snip-editor-responsibilities) on the snip repo). The process should also detail practical details such as who the current editors are, a more nuanced style guide, and examples of good improvement proposals from other ecosystems.

**Additional context**
Here is the content from the Ethereum ecosystem which describes this well:
https://ethereum.org/en/eips/
https://eips.ethereum.org/

https://community.starknet.io/t/snips-process-revival/114075/4?u=mempoolsurfer

**Comment by LandauRaz** [comment]
Hey @JorikSchellekens, given that this information is already available on starknet.io: https://www.starknet.io/developers/snips/ do you still feel it should be added to the docs?

**Comment by LandauRaz** [comment]
Closed due to inactivity.
