### ISSUE TITLE
Wrong field in v1 (deprecated) hash calculation documentation

### ISSUE THREAD

**Issue by thiagodeev** [starknet-io/starknet-docs#1284]
One of these two lines must be wrong. It contains "1" but all other transactions contain "0", also the description says "0". It's confusing.
https://github.com/starknet-io/starknet-docs/blob/72714abc276e048ba5779697afbebba9691e8430/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transactions.adoc?plain=1#L408

https://github.com/starknet-io/starknet-docs/blob/72714abc276e048ba5779697afbebba9691e8430/components/Starknet/modules/architecture_and_concepts/pages/Network_Architecture/transactions.adoc?plain=1#L419

**Comment by Benjtalkshow** [comment]
Hello,
I can help in summarizing the transaction types and hash calculations. I have a clear understanding of the DECLARE, INVOKE, and DEPLOY_ACCOUNT transactions, including their versions and hash calculation methods. Can you assign this to me?

**Comment by stoobie** [comment]
@Benjtalkshow This issue is just a simple fix. Would you like to do it? If so, feel free.

You're always welcome to open a PR if you feel that something could be explained better than it is, but this issue is very specific in its scope.

**Comment by Benjtalkshow** [comment]
> @Benjtalkshow This issue is just a simple fix. Would you like to do it? If so, feel free.
> 
> You're always welcome to open a PR if you feel that something could be explained better than it is, but this issue is very specific in its scope.

@stoobie I will do it?

**Comment by stoobie** [comment]
@Benjtalkshow  It's yours. The "1" in line 408 should be "0".
