### ISSUE TITLE
Adding a page on fee estimation

### ISSUE THREAD

**Issue by odednaor** [starknet-io/starknet-docs#1293]
**Is your feature request related to a problem? Please describe.**
The docs don't contain a description of how to calculate fees (should be done based on the `starknet_estimateFee` call), or how to map the fields returned by the call to the `resource_bounds` dictionary of v3 transactions. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stoobie** [comment]
@odednaor Did you already open a PR for this?

**Comment by LandauRaz** [comment]
The answer is [yes](https://docs.starknet.io/architecture-and-concepts/network-architecture/transactions/#v3-fee-estimation), so closing this one.
