### ISSUE TITLE
bug: search doesn work

### ISSUE THREAD

**Issue by enitrat** [starknet-io/starknet-docs#1344]
**Describe the bug**

Search feature doesn't work and returns pages not found.
**To Reproduce**

Search for "parallelization"
Click first link

<img width="764" alt="image" src="https://github.com/user-attachments/assets/48f47992-e38e-41f8-9534-8a8602111a09">

**Expected behavior**
I get redirected to the relevant page

**Comment by LandauRaz** [comment]
Hey @enitrat, thanks for the feedback!
This should be fixed now, can you verify that this is indeed the case for you too?

**Comment by LandauRaz** [comment]
Closed due to inactivity.
