### ISSUE TITLE
bug: event page is outdated

### ISSUE THREAD

**Issue by enitrat** [starknet-io/starknet-docs#1348]
https://docs.starknet.io/architecture-and-concepts/smart-contracts/starknet-events/#emitting_events

This is not longer up to date since Cairo 2.0, the syntax corresponding to events has changed and is now based on the Events enum. 

I recommend either linking the Cairo Book or updating this, as this is confusing the response created by LLMs (and confuses users as well!)

**Comment by LandauRaz** [comment]
Addressed in #1429. Thanks for bringing this to our attention! 🙏
