### ISSUE TITLE
remove v1 -> v2 migration

### ISSUE THREAD

**Issue by enitrat** [starknet-io/starknet-docs#1351]
https://docs.starknet.io/architecture-and-concepts/smart-contracts/contract-syntax/#migrating-a-contract-from-cairo-v1-to-cairo-v2

This page should no longer be needed one year later and is confusing from an SEO perspective when looking for informations about the syntax of contracts.

**Comment by Mobarak786** [comment]
@enitrat  Are you actually  means to delete the entire page from the repo...

**Comment by LandauRaz** [comment]
Resolved by PR #1396, thanks for the input!
