### ISSUE TITLE
The link is not working

### ISSUE THREAD

**Issue by Olexandr88** [starknet-io/starknet-docs#1428]
This link in the documentation does not work 

What happens when you submit a PR?

When you submit a PR, the [Starknet Docs team](https://github.com/orgs/starknet-io/teams/starknet-docs) reviews the PR and arranges further technical reviews as necessary. If the PR requires changes, the reviewers add comments to the PR. We might request that you make the changes, or let you know that we incorporated your content in a different PR. Occasionally, we might add commits to the original PR directly. When the PR has been reviewed and all updates are complete, the documentation team merges the PR and applies it to the valid version(s).

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by LandauRaz** [comment]
Hey @Olexandr88, which link are you referring to exactly?

**Comment by Olexandr88** [comment]
Hey @LandauRaz here is the link Starknet Docs team](https://github.com/orgs/starknet-io/teams/starknet-docs)

**Comment by LandauRaz** [comment]
Got it, the link is now [removed](https://github.com/starknet-io/starknet-docs/commit/4e375cb7f5ac69e8e15c826fd8a301c3643b89da). Thanks for bringing this to our attention! 🙏

**Comment by Olexandr88** [comment]
Thank you very much for the reward
