### ISSUE TITLE
Explicitly state that failing `call_contract_syscall` can't be caught and will revert the entire tx

### ISSUE THREAD

**Issue by enitrat** [starknet-io/starknet-docs#709]
**Is your feature request related to a problem? Please describe.**

It's not written anywhere (is it?) that, quoting Ariel,

>  an internal call can't return Err(_), as this is not handled by the sequencer and the Starknet OS.

 I think it's very important to have it as a warning in the documentation, as it's a pattern that already a lot of developers assume is correct - but once deployed, it will lead to incorrect results

**Describe the solution you'd like**
A warning [here](https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/system-calls-cairo1/) about this specific case

**Describe alternatives you've considered**

**Additional context**

**Comment by JameStark** [comment]
Thanks for flagging this. A PR has been opened adding a warning:
https://github.com/starknet-io/starknet-docs/pull/774
