### ISSUE TITLE
command not found: starknet

### ISSUE THREAD

**Issue by wenjoy** [starknet-io/starknet-docs#793]
**Describe the bug**
I follow instruction of quick start at `starknet new_account --account <account_name>` get this error:
command not found: starknet

**To Reproduce**
Follow quick start instruction at here https://docs.starknet.io/documentation/quick_start/environment_setup/

**Expected behavior**
It should be successful

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
starkli --version : 0.1.13 (305a9b1)

It's really bad for official website's quick start has such obvious mistake, previously steps even not mention a word about `starknet`.

**Comment by JameStark** [comment]
Hello, 

Thank you for flagging, we appreciate the feedback.

The environment setup has now been updated inline with a shift to support of Starkli as the official CLI tool for Starknet. 

Please see the updated guide: https://docs.starknet.io/documentation/quick_start/environment_setup/#starkli_installation
