### ISSUE TITLE
starkli account fetch command unexpected argument error

### ISSUE THREAD

**Issue by blhq111** [starknet-io/starknet-docs#812]
was following the Starknet developer documentation and encountered an issue while trying to use the starkli account fetch command. The documentation suggests the following command:

bash
Copy code
starkli account fetch 0x0--------C--F2 ~/starkli-wallets/deployer/account.json
However, when I tried to execute this command, I received the following error:

vbnet
Copy code
error: unexpected argument '/Users/xxxx/starkli-wallets/deployer/account.json' found

Usage: starkli account fetch [OPTIONS] <ADDRESS>
Expected Behavior:

I expected the starkli account fetch command to execute without errors, as per the documentation.

Actual Behavior:

The command results in an unexpected argument error.

Steps to Reproduce:

Execute the following command as per the documentation:
bash
Copy code
starkli account fetch 0x0--------C--F2 ~/starkli-wallets/deployer/account.json
Additional Information:

Operating System: [Your OS]
Starknet Version: [Version, if applicable]
Any other relevant information.
Please advise on the correct usage of the starkli account fetch command or update the documentation to reflect the correct usage.

**Comment by stoobie** [comment]
@ArielElp PTAL

**Comment by ArielElp** [comment]
I think you were missing `--output`, in any case the following example does work:

```
starkli account fetch 0x772b4b6e99d7d69ddd41dad3014acd69c6d10e50eed24fbbe5acd358d6b8a59 --output ./test_fetch.json --rpc https://starknet-mainnet.public.blastapi.io/rpc/v0_6
```
