### ISSUE TITLE
Function name heading should clearly delineate section

### ISSUE THREAD

**Issue by LucasLvy** [starknet-io/starknet-docs#898]
This is how the functions are displayed currently in the [**StarkGate function reference**](https://docs.starknet.io/documentation/tools/starkgate_function_reference/):
![Screenshot 2023-10-24 at 17 07 41](https://github.com/starknet-io/starknet-docs/assets/70894690/efb911a5-21ff-4de7-b6e3-c1d5824a32ef)

It's kinda hard to see that we are in another function because everything is in the same color and there's no clear separation. I think that the function names (which are titles) in this page should be easily identifiable either by using another color or something else.

**Comment by stoobie** [comment]
Need to edit the starknet-docs-antora-ui repo.

**Comment by stoobie** [comment]
This issue was addressed by https://github.com/starknet-io/starknet-docs-antora-ui/pull/36.
