### ISSUE TITLE
Typo: releasing-starknet-docs-on-github

### ISSUE THREAD

**Issue by bjcd** [starknet-io/starknet-docs#931]
There is a small typo here: https://github.com/starknet-io/starknet-docs#releasing-starknet-docs-on-github

In the section "Releasing Starknet docs on Github," there's a sentence that says "Your local version of master now includes all the changes from the **remove** version of dev." The word "remove" should be "remote"  and the sentence should read "Your local version of master now includes all the changes from the **remote** version of dev."

**Comment by stoobie** [comment]
Thanks for this @bjcd .
