### ISSUE TITLE
Correct the deploy account page and provide more ways to deploy accounts using UDC

### ISSUE THREAD

**Issue by odednaor** [starknet-io/starknet-docs#935]
In the deploying new accounts page: https://docs.starknet.io/documentation/architecture_and_concepts/Accounts/deploying_new_accounts/#validate_deploy

When using the `deploy_account` transaction, the deployed contract must have a `__validate_deploy__` entrypoint. Currently this is mentioned as optional.

One can also deploy an account using the [deploy](https://docs.starknet.io/documentation/architecture_and_concepts/Smart_Contracts/system-calls-cairo1/#deploy) syscall. There is a convenient option to use this syscall using the [Universal Deployer Contract (UDC)](https://docs.openzeppelin.com/contracts-cairo/0.6.1/udc) by OpenZeppelin.

**Comment by stoobie** [comment]
@odednaor Does #1011 cover this?

**Comment by stoobie** [comment]
Addressed by #1163.
