### ISSUE TITLE
*Seeking Contribution* PRs from forks are not generating preview builds.

### ISSUE THREAD

**Issue by stoobie** [starknet-io/starknet-docs#938]
**Describe the bug**

When a PR originates from a forked repo, it does not generate an HTML preview to enable reviewing and testing the PR in a browser prior to merging.

The issue becomes visible when the runner runs the[ _Commit changes_](https://github.com/starknet-io/starknet-docs/blob/63c5c84b176e0dfa47bbb28e1ff1484e6f667835/.github/workflows/pull_request.yml#L75) step in the pull_requent.yml workflow.

**To Reproduce**

1. Fork (and optionally clone) the starknet-docs repo.
2. Create a new branch and make a small change in an .adoc file.
3. Push the new branch and create a new PR.

**Expected behavior**
You should see this in **Conversaton** tab of the PR
![image](https://github.com/starknet-io/starknet-docs/assets/39279277/b3057536-3332-487b-8120-e75a988f314c)

You should also see a link like this one (with the correct PR-number):
![image](https://github.com/starknet-io/starknet-docs/assets/39279277/6483335a-6d7c-4824-a8db-4607c9046f55)

**Comment by stoobie** [comment]
So far I've been unable to fix this issue. If you want to take a look and try to fix it, your contribution will be very much appreciated.

**Comment by stoobie** [comment]
This is a duplicate of #1043

**Comment by stoobie** [comment]
Unfortunately, #1182 was required to revert the PRs #1097 and #1152 because of a security vulnerability that was introduced by the `pull_request_target` event.

So we are back to where we started with this one.

**Comment by xiaolou86** [comment]
I am very sorry. Let other people come to resolve it firstly.

**Comment by xiaolou86** [comment]
Generally speaking, the pull_request_target event is more security than pull_request event, maybe there is something wrong with the token.

**Comment by stoobie** [comment]
This is closed by #1250.
