### ISSUE TITLE
feat: add `l1_handler_transaction` version table

### ISSUE THREAD

**Issue by glihm** [starknet-io/starknet-docs#969]
**Is your feature request related to a problem? Please describe.**
Currently, we have a table for transaction version, but `l1_hander_transaction` is not in this table. This is important to have in order to compute the transaction hash.

**Describe the solution you'd like**
Add `l1_handler_transaction` version (which is 0 currently) to the transaction table in the page `Transaction Types`. Or a new table in the `L1-L2 Messaging` page where the computation of `l1_handler_transaction` actually is.

I would be happy to open a PR if this suggestion is approved.

**Comment by stoobie** [comment]
@glihm Please feel free to open a PR and assign me as the reviewer.

**Comment by stoobie** [comment]
@glihm Are you still interested? This fell completely off my radar. I'm checking with the experts on their thoughts about this. Will get back to you. Feel free to ping me.

**Comment by tdelabro** [comment]
@stoobie yeah that looks like a great idea. The truth is I don't care about where it goes exactly, as long as the current version number for `l1_handler_transaction` is indeed specified somewhere. The main issue to me was that the actually number was not mentioned anywhere at all.

**Comment by stoobie** [comment]
@glihm Are you in our Telegram channel? Would love to touch base with you there: https://t.me/+9VC94EQA8dY4ZTZh

**Comment by glihm** [comment]
@stoobie sorry for the delay and thanks again for pinging. PR open, please don't hesitate any feedback on the PR. 🫡
