### ISSUE TITLE
Taking 

### ISSUE THREAD

**Issue by Debashis24k** [starknet-io/starknet-docs#973]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by stoobie** [comment]
@Debashis24k It's not clear what this issue is about. Did you open a PR to address this? I'm closing this for now. If the issue you saw is not addressed, feel free to reopen with an explanation and a pointer to any PR that addresses this.
